# Generated by Django 6.1 on 2026-10-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0005_certificacionlote_loterecepcionado_certificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacionlote',
            name='costo_auditoria',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='fundoproductor',
            name='cupo_diario_lotes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='loterecepcionado',
            name='estado_evaluacion',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
    ]
