# Generated by Django 6.1 on 2026-10-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0006_certificacionlote_costo_auditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loterecepcionado',
            name='porcentaje_descarte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
